### ISSUE TITLE
NoClassDefFoundError after compiling groovy script to executable

### ISSUE THREAD

**Issue by todd-elvers** [todd-elvers/groovy-to-exe-converter#9]
Consider the following Groovy script:

``` groovy
class ClassOne {

    public static void main(String[] args) {
        new ClassOne().print()
        new ClassTwo().print()
    }

    void print() {
        println "ClassOne successfully instantiated"
    }
}

class ClassTwo {
    void print() {
        println "ClassTwo successfully instantiated"
    }
}
```

When the above is executed in GroovyConsole, the results are what you'd expect:

```
ClassOne successfully instantiated
ClassTwo successfully instantiated
```

However, if this script is compiled into an executable file w/ g2exe, then running it yields:

```
ClassOne successfully instantiated
Exception in thread "main" java.lang.NoClassDefFoundError: ClassTwo
        at ClassOne.main(Example.groovy:5)
Caused by: java.lang.ClassNotFoundException: ClassTwo
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 1 more
```

This is a bug and a pretty nasty one at that.

**Comment by todd-elvers** [comment]
This also results in a NoClassDefFoundError when compiled via g2exe, but runs fine in the GroovyConsole:

``` groovy
class ClassOne {
    void print() {
        println "ClassOne successfully instantiated!"
    }
}

new ClassOne().print()
```

**Comment by todd-elvers** [comment]
Resolved this issue.  The issue was I was being too specific in terms of what kind of classes would be bundled into the JAR file when converting from a Groovy script to a JAR.  Now, all classes that get generated by compiling the Groovy Script are included in the JAR that g2exe creates.
